let events = {
  JOIN_GAME: 'JOIN_GAME',
  UPDATE_PLAYER_POSITION: 'UPDATE_PLAYER_POSITION',
  JOIN_SUCCESSFUL: 'JOIN_SUCCESSFUL',
  OPPONENT_CONNECTED: 'OPPONENT_CONNECTED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  GAME_UPDATE_FROM_CLIENT: 'GAME_UPDATE_FROM_CLIENT',
  GAME_UPDATE_FROM_SERVER: 'GAME_UPDATE_FROM_SERVER',
}

export default events;
