let events = {
  JOIN_GAME: 'JOIN_GAME',
  UPDATE_PLAYER_POSITION: 'UPDATE_PLAYER_POSITION',
  JOIN_SUCCESSFUL: 'JOIN_SUCCESSFUL',
  OPPONENT_CONNECTED: 'OPPONENT_CONNECTED'
}

export default events;
